[package]
# Semantic Versioning is used: https://semver.org/
version = "0.8.6"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["ANSYS"]

# The title and description fields are primarily for displaying extension info in UI
title = "ANSYS Omniverse Geometry Service Server"
description = "A geometry synchronization service that enables export of geometry scenes from ANSYS products to Omniverse."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/ansys/pyensight"

# One of categories for UI.
category = "simulation"

# Keywords for the extension
keywords = ["ANSYS", "EnSight", "PyEnSight", "Fluent", "kit"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
# "omni.kit.pipapi" = {}
"omni.client" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import ansys.geometry.service".
[[python.module]]
name = "ansys.geometry.service"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]

[settings]
# CLI setting defaults (note: "help" and "run" are also supported)
exts."ansys.geometry.service".dsgUrl = "grpc://127.0.0.1:5234"
exts."ansys.geometry.service".omniUrl = "omniverse://localhost/Users/test"
exts."ansys.geometry.service".securityCode = ""
exts."ansys.geometry.service".temporal = "0"
exts."ansys.geometry.service".vrmode = "0"
exts."ansys.geometry.service".normalizeGeometry = "0"
exts."ansys.geometry.service".timeScale = "1.0"
